---
name: 'publish-gem-to-rubygems'
author: 'Dan Webb'
description: 'Run publish Gems to Rubygems'
runs:
  using: 'docker'
  image: docker://ghcr.io/actionshub/publish-gem-to-rubygems:1.0.0
branding:
  icon: 'edit-3'
  color: 'red'
